name: autocall
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - lightgbm
  - xgboost
  - fastapi
  - uvicorn
  - pydantic
  - pytest
